### ISSUE TITLE
Worldedit Restrictions

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TotalFreedomMod#431] opened 2015-02-14 22:12 UTC
How do I make it so some world edit blocks are disabled/forbidden? I know this is should to be under the TotalFreedom/WorldEdit but no one checks it there.
What i meant is Worldedit Restrictions on blocks. Like lava, bedrock.
Ex:
If I use a forbidden block, it would auto de-op be and broadcast that i tried to use it
looperXD tried to use : lava
You are now no longer OP
something like that

**Comment by Wild1145** [comment] 2015-02-14 22:29
By using the worldedit under TotalFreedom/WorldEdit

**Comment by JeromSar** [comment] 2015-02-14 23:30
I think this is a duplicate of https://github.com/TotalFreedom/worldedit/issues/6?

**Closed by JeromSar** 2015-02-14 23:30 UTC
Labels: Question
