### ISSUE TITLE
/glist banip <playername>

### ISSUE THREAD

**Issue by aggelosQQ** [TotalFreedom/TotalFreedomMod#882] opened 2015-10-27 16:11 UTC
"Hello.

If a player is imposing as an OP, you would want to ban them, but without banning the username. If we could do 24-hour IP bans, without effecting the username, that would be good. I would suggest a new command such as "/glistip ban <User>", which would only ban the user's IP, and not the username."

Read more: http://totalfreedom.boards.net/thread/30344/glist-ban-ip?page=1#ixzz3pmkmZOPG

**Comment by JeromSar** [comment] 2015-10-27 16:38
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/871

**Closed by JeromSar** 2015-10-27 16:38 UTC

**Comment by PremintexMC** [comment] 2015-10-27 16:56
Vouch
