### ISSUE TITLE
Add command /ghost for invisibility

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1881] opened 2016-10-09 18:44 UTC
It does give you invisibility when you type it in, and /ghost clean to clean the invisibility from admins, that command can be done from console, and when you type in /invis it shows that OPs: invisibleop1 invisibleop2 Admins: invisibleadmin1

**Comment by JeromSar** [comment] 2016-10-09 19:16
Duplicate of/alternate to https://github.com/TotalFreedom/TotalFreedomMod/issues/266

**Closed as completed by JeromSar** 2016-10-09 19:16 UTC
Labels: Duplicate, Issue: Enhancement
