### ISSUE TITLE
Add multi-line MOTD support

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#868] opened 2015-10-19 20:42 UTC
Putting "\n" in the MOTD should separate everything after it into a second line, instead of having to use spaces to achieve a multi-line MOTD.

**Comment by JeromSar** [comment] 2015-12-28 13:43
@ShadowArmadyl Isn't this a feature already? Could you test this?

**Comment by OnlineRepz** [comment] 2015-12-29 04:34
@JeromSar, I have tested it and it's working.

**Comment by DUFCLiam** [comment] 2015-12-29 11:01
@JeromSar, Can I ask something quickly

**Comment by JeromSar** [comment] 2015-12-29 11:03
@DUFCLiam Go ahead! :)

**Comment by DUFCLiam** [comment] 2015-12-29 11:05
Say an issue is like #70 then how is that a duplicate? As that one can be forgotten about, and the current issue is like #9999.

**Comment by DUFCLiam** [comment] 2015-12-29 11:05
Would that still count?

**Comment by JeromSar** [comment] 2015-12-29 11:12
@DUFCLiam Perhaps. But mostly, when an idea is abandoned, it is abandoned forever. Issues aren't deleted so you can always search for them in the issue browser. :)

**Comment by DUFCLiam** [comment] 2015-12-29 12:50
Thanks @JeromSar thats how most of my ones are duplicates :P

**Comment by ShadowArmadyl** [comment] 2015-12-29 18:10
This is only a feature for the Minecraft config - not the TFM config, @JeromSar

**Comment by JeromSar** [comment] 2015-12-29 21:35
@ShadowArmadyl Pretty sure TFM supports this out-of-the-box.

**Comment by Wild1145** [comment] 2015-12-31 01:03
This *should* be supported in both TFM and Minecraft by default as I believe its just the way that the YAML file is parsed... Regardless of the implementation of it.

**Comment by ShadowArmadyl** [comment] 2016-01-13 21:58
TFM does not support this out of the box, because I've tried it before on one of my previous TFM-based servers. @JeromSar

**Comment by Wild1145** [comment] 2016-01-20 16:10
@ShadowArmadyl Please share the MOTD config you tried to use because this is something that vanilla minecraft supports out of the box...

**Comment by ShadowArmadyl** [comment] 2016-02-16 02:55
Bump - I took a picture of what happens when you enter this into TFM config.
https://i.gyazo.com/ffd0927dd443bda30ab3215b4672a486.png

**Comment by AvalancheYT** [comment] 2016-02-16 05:33
You can't do it in TFM Configuration. You can code it in TFM_ServerListener.java and add first motd and 2nd motd in motd

**Comment by ShadowArmadyl** [comment] 2016-02-23 01:58
^ my point is made. I'd like this to be opened back up as this is a valid issue.

**Comment by JeromSar** [comment] 2016-03-10 16:08
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/747

**Closed by JeromSar** 2016-03-10 16:08 UTC
Labels: Issue: Enhancement
