### ISSUE TITLE
No tempbans for famous player names

### ISSUE THREAD

**Issue by OxLemonxO** [TotalFreedom/TotalFreedomMod#379] opened 2014-12-03 17:25 UTC
Currently, tempban only bans by name, so a famous player name bypasses that and a person can login again, bypassing the ban. So, make tempban ban by IP too?

**Comment by JeromSar** [comment] 2015-04-26 23:01
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/499

**Closed by JeromSar** 2015-04-26 23:01 UTC
Labels: Bug
