### ISSUE TITLE
Banning Improvement

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#895] opened 2015-11-13 23:30 UTC
I think you should make it you need/optionally need a ban reason for /noob or /tban or /glist or on the permban list, it would help a lot.

**Comment by JeromSar** [comment] 2015-11-14 21:26
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848

**Closed by JeromSar** 2015-11-14 21:26 UTC
Labels: Duplicate, Issue: Enhancement
