### ISSUE TITLE
"/v" - an Admin Command.

### ISSUE THREAD

**Issue by vj13573** [TotalFreedom/TotalFreedomMod#345] opened 2014-10-23 19:59 UTC
It's a suggestion;
Admins should have access to "/v" which is short for "/vanish" - It's a Essentials command, but during normal servers, only OPs it works, it hides their TAB name and makes them invis, why not also have one for Admins? Only Admins should have access to this command, and this would be useful as trolls and griefers would be thinking "ooh, there's no admins on, now we can grief and troll xD" or etc, thats why, admins can use this command to go invis and it hides their name in TAB, especially when admins name appears in colour on TAB, which makes it obvious to see for everyone, it should also hide their name under "/list" or "/list -a" or any other Alias command for that, however, admins and theirself can see their name on TAB, only for OPs they can't see, so the suggestion is, make "/v" or "/vanish" a command for admins ONLY. Just like the normal Essentials one, but make sure it hides them for OPs instead.

**Comment by JeromSar** [comment] 2015-01-11 10:34
Closed, duplicate of #226

**Closed by JeromSar** 2015-01-11 10:34 UTC
Labels: enhancement

**Comment by DUFCLiam** [comment] 2016-03-02 18:08
This is not a duplicate of #226

**Comment by Wild1145** [comment] 2016-03-02 18:18
It is however a duplicate, there is no need to be nit-picky.

**Comment by Adaptified** [comment] 2016-03-03 12:59
No, this issue and the other one have nothing to do with each other. @Wild1145

**Comment by Wild1145** [comment] 2016-03-03 14:16
@Adaptified Correct, however it is still a duplicate. @JeromSar Is only human and likely confused it with the wrong issue number. The duplicate is still valid, so as I Said before, there is no need to be nit-picky.

**Comment by JeromSar** [comment] 2016-03-03 14:59
https://github.com/TotalFreedom/TotalFreedomMod/issues/266 is the actual duplicated issue. My bad.
