### ISSUE TITLE
Download logs

### ISSUE THREAD

**Issue by mayokek** [TotalFreedom/TotalFreedomMod#1968] opened 2017-02-09 12:14 UTC
@OxLemonxO already got the code, I am just creating the issue.
So how this works - it would check if the ip accessing the downloading logs page (HTTPD) and if it is supered, it would let them access to it and download logs. It can be useful so mark don't have to pull the logs and give it to us.

**Comment by ghost** [comment] 2017-02-11 00:28
This is already added, you can already download logs.

**Comment by mayokek** [comment] 2017-02-11 01:45
@Commodore64x, actually, you can't download logs.

**Comment by Wild1145** [comment] 2017-02-11 14:50
@Commodore64x Please explain how you can currently download logs?

**Comment by ghost** [comment] 2017-02-15 08:16
@Wild1145 using the log password defined in config:
http://play.totalfreedom.me:28966/logs?password={password}

**Comment by mayokek** [comment] 2017-02-15 08:26
That's just to view the latest logs pulled from the server...

**Comment by Wild1145** [comment] 2017-02-15 15:40
I have confirmed that the /logs module does only show the latest log and the scope of this issue is to allow for all logs in the logs folder to be downloadable. The issue is still valid.

**Comment by Wild1145** [comment] 2019-09-14 19:31
Resolved in https://github.com/TotalFreedom/TotalFreedomMod/commit/de55ead09a00018da5c21e44c48f71297e223543

**Closed as completed by Wild1145** 2019-09-14 19:31 UTC
Labels: Issue: Enhancement, Issue: Accepted
