### ISSUE TITLE
Gtfo params

### ISSUE THREAD

**Issue by ImScoop** [TotalFreedom/TotalFreedomMod#700] opened 2015-06-11 19:35 UTC
Currently this is the first part of /gtfo

It returns the usage

which is currently /gtfo <partialname>

it needs to be /gtfo <partialname> <reason>

I will make a PR

**Comment by JeromSar** [comment] 2015-06-11 19:53
@Scuph I'm confused as to what exactly you're trying to say here. Could you be clearer?

**Comment by Scuph** [comment] 2015-06-11 19:54
@JeromSar If you don't enter enough arguments on gtfo, it shows the parameters, '/gtfo <partialname>'
it should be '/gtfo <partialname> <reason>

**Comment by JeromSar** [comment] 2015-06-11 19:56
@Scuph Eh?

**Comment by Scuph** [comment] 2015-06-11 19:56
@JeromSar Stupid github settings, let me fix it

**Comment by Wild1145** [comment] 2015-06-12 12:26
@JeromSar Its because github formats tags like [ img ] so when he was explaining it they were removed and replaced with empty text.

**Comment by JeromSar** [comment] 2015-10-12 06:50
Duplicate of #848

**Closed by JeromSar** 2015-10-12 06:50 UTC
Labels: Issue: Enhancement

**Comment by Wild1145** [comment] 2015-10-20 21:00
@JeromSar Not sure what the point in creating another issue was?

**Comment by ImScoop** [comment] 2015-10-21 04:01
Yeah, that's pointless @Wild1145

**Comment by DUFCLiam** [comment] 2016-03-10 16:58
Not a duplicate @JeromSar

**Comment by JeromSar** [comment] 2016-03-10 18:01
@Wild1145 @Adaptified @DUFCLiam That issue was made to replace several (10+ literally) issues with (somewhat) the same suggestion. If you were to have actually read the issue (#848), you would have known this.
