### ISSUE TITLE
Tempbans not working

### ISSUE THREAD

**Issue by FlexxPro** [TotalFreedom/TotalFreedomMod#528] opened 2015-04-01 14:31 UTC
I've tempbanned this guy multiple times, he keeps coming back. 
[14:27:49] [Server thread/INFO]: FlexxPro issued server command: /tempban tomc 5 minor-grief
[14:27:49] [Server thread/INFO]: [PREPROCESS_COMMAND] FlexxPro(FlexxPro): /tempban tomc 5 minor-grief
[14:27:49] [Server thread/INFO]: [PLAYER_COMMAND] FlexxPro (FlexxPro): /tempban tomc 5 minor-grief
[14:27:49] [Server thread/INFO]: FlexxPro - Temporarily banned Tomc2808 until 2015-04-01 at 14:27:54 GMT, Reason: "minor-grief (FlexxPro)"
[14:27:50] [Server thread/INFO]: [EXIT] Tomc2808 left the game.
[14:27:50] [Server thread/INFO]: Tomc2808 lost connection: FlexxPro - Temporarily banned Tomc2808 until 2015-04-01 at 14:27:54 GMT, Reason: "minor-grief (FlexxPro)"
[14:27:50] [Server thread/INFO]: [EXIT] Tomc2808 left the game.
[14:27:50] [Server thread/INFO]: Tomc2808 left the game.
[14:28:02] [User Authenticator #268/INFO]: UUID of player Tomc2808 is d66d558b-1fc9-3d8f-add9-d4e41a9a86c1
[14:28:03] [Server thread/INFO]: [JOIN] Tomc2808 (d56e3273-37ef-4661-8fd2-9282c61a6803) joined the game with IP address: 91.34.9.5
[14:28:03] [Server thread/INFO]: Tomc2808[/91.34.9.5:62389] logged in with entity id 7062 at ([Woosh] 65.54245340066792, 104.0, 289.56557666545547)

**Comment by ImALuckyGuy** [comment] 2015-04-02 00:21
The problem is, it seems to work sometimes and other times not. I'm thinking it has something to do with UUIDs. I'm not exactly sure though.

**Comment by JeromSar** [comment] 2015-04-26 22:40
Duplicate of #499

**Closed by JeromSar** 2015-04-26 22:40 UTC
Labels: Bug, Duplicate
