### ISSUE TITLE
Block DeathPotions

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#736] opened 2015-06-29 07:16 UTC
hello, today i got on and User_ made a redstone lag machene and no sa was on.
In code i found that you can do a certain bolean which stops placing of blocks, potions, etc.
I hope it stops, 

Many thnks ipatty.

**Comment by Wild1145** [comment] 2015-06-29 20:44
The question is how...

**Comment by ScuphGamingUK** [comment] 2015-06-30 03:32
OnPotionSplash in the entitylistener

@Wild115

**Comment by LegendIsAwesomes** [comment] 2015-06-30 20:04
@ScuphGamingUK  That will stop every splash potion that is splashed, Again taking away the name 'Total FREEDOM'

**Comment by Wild1145** [comment] 2015-06-30 20:31
@LegendIsAwesomes @ScuphGamingUK I think the event is the right place, but its getting the exact potion and thats something I am not sure on, because I have never done anything with potions using Bukkit API. If its possible thats just dandy, if not we need to figure out another way to work around it.

**Comment by ScuphGamingUK** [comment] 2015-06-30 21:04
@LegendIsAwesomes Stick to what you actually know and stop talking about what you don't. It would check if there is a damage event on the player during the splash event, and if it does, set the players health to max and remove the potion effect. Hence why you have no idea what you are talking about.

**Comment by Wild1145** [comment] 2015-06-30 21:36
@ScuphGamingUK Get back in your box, and respect everyone on this repo before the good sir @JeromSar smashes a ban hammer on your head faster than you can say totalfuckingfreedom. This is a place for discussion not bashing, wanna bash someone, go on the server and do it and see how quickly I come on and suspend your ass back to hell.

**Comment by SlicedCaek** [comment] 2015-07-01 01:03
@ScuphGamingUK @Wild1145, Calm down, can ya!

ONT: Can you explain more?

**Comment by ScuphGamingUK** [comment] 2015-07-01 01:18
@Wild1145 He sent me a message asking how stupid I was for suggesting that, so I decided to take it here. I will stop, but I dont give a shit what rank you are, do NOT threaten me.

**Comment by SlicedCaek** [comment] 2015-07-01 01:21
@ScuphGamingUK, Next time, can you take this to PM.

Please bring this back on topic.

**Comment by Wild1145** [comment] 2015-07-01 01:44
@ScuphGamingUK If you had a single ounce of respect for the other people on this project I would not need to comment at all, however when you act like a 3 year old spoilt brat I will damm well call you on your bullshit. If you are abusive towards other people regardless of their rank my "threat" to suspend you will be of no worries to me. Grow up and act mature here or don't bother commenting. You have anything else to say to me youre welcome to email or PM me.

**Comment by SlicedCaek** [comment] 2015-07-01 02:27
Requesting Someone to delete the drama posts

**Comment by JeromSar** [comment] 2015-07-01 08:39
Cleaned up the drama posts.

@ScuphGamingUK @Wild1145 Please take your insults away from this repository. We're here to debate, everyone's opinion is vital, but you shouldn't got beyond your post and rage about it.

**Comment by Hockeyfan360** [comment] 2015-07-05 02:11
Check for a regeneration potion + a potency of 29?

**Comment by PattyToTheWatty** [comment] 2015-07-05 03:41
You know, this would be impossible. Nearly 200+ enchantments of potency. I might just close this now.

**Comment by Adaptified** [comment] 2015-07-05 04:21
@PattyToTheWatty This is not impossible, easily fixable.

**Comment by PattyToTheWatty** [comment] 2015-07-05 06:47
Reopended then.

**Comment by looperXD** [comment] 2015-07-08 13:13
Death pots are either negative or overload values. 29 & 120 are overload.

**Comment by EXPLODINGTNT001** [comment] 2015-07-23 20:45
Death Potions are spawned by this manner: 
/give <user> 373 1 16385 {CustomPotionEffects:[{Id:6,Amplifier:125­,Duration:10000}]}
Make sure you NEVER give that to trolls.

**Comment by PattyToTheWatty** [comment] 2015-07-23 21:27
You may want to delete that :/

**Comment by xDestroyer217** [comment] 2015-07-24 04:14
@EXPLODINGTNT001 Nice one dipshit, now everyone knows.

**Comment by Wild1145** [comment] 2015-07-24 11:40
@xDestroyer217 Yes, including the developers... Its not like OP's couldnt just google it anyway... Take a chill pill.

**Comment by Hockeyfan360** [comment] 2015-07-26 15:26
I am working on a fix.

**Comment by JeromSar** [comment] 2015-08-22 09:09
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/690

**Closed by JeromSar** 2015-08-22 09:09 UTC
Labels: Issue: Enhancement

**Comment by Elephants111** [comment] 2015-08-25 21:59
Also, new death potion... /give [username] potion 1 16385 {CustomPotionEffects:[{Id:6,Amplifier:253}]}

**Comment by Elephants111** [comment] 2015-08-27 22:38
@JeromSar -Bump
