### ISSUE TITLE
Smite Addition Suggestion

### ISSUE THREAD

**Issue by ImScoop** [TotalFreedom/TotalFreedomMod#393] opened 2015-01-07 21:59 UTC
I recommend giving the admins an option (not mandatory when performing the cmd) to give a reason while smiting, so /say isn't needed. It would be /smite [playername] [reason(optional)], then it would be /smite Guy No &k

Guy has been a naughty, naughty boy!
Reason: No &k (theLAZYway01)
Guy Died.     

               (When the admin does the cmd, make the cmd put the IGN in Parentheces)

**Comment by Wild1145** [comment] 2015-01-07 22:16
Sounds good, saves having to smite someone then doing a /say to tell people why, keeps it cleaner and required minimal changes to the command.

**Comment by BestMcPlayers** [comment] 2015-01-07 23:52
This sounds like a good idea to me. I wouldn't mind this, although it's going to take some time to get use to it.

**Comment by theLAZYway01** [comment] 2015-01-10 01:47
But Make sure, (if it is possible), At the end of the reason, it automatically puts the admins name it parentheces! so we dont have to type it. Because with this feature, you're forgetting that the OPs that get smited will not know who smited them, and might need too, with /say, they saw the admins name, so make sure the admins name in parentheces is automatically included!

**Comment by theLAZYway01** [comment] 2015-01-10 01:50
If that isn't possible than change the cmd message from:

Player has been a naughty, naughty boy
to
(Adminname) has smited (Playername) for being naughty!
Reason: (Optional)

**Comment by JeromSar** [comment] 2015-10-12 06:48
Duplicate of #848

**Closed by JeromSar** 2015-10-12 06:48 UTC
Labels: Issue: Enhancement

**Comment by ImScoop** [comment] 2015-10-12 19:30
This was made before that @JeromSar, lol.

**Comment by JeromSar** [comment] 2015-10-12 20:34
@ImScoop I'm aware.

**Comment by DUFCLiam** [comment] 2016-03-10 16:58
Not a duplicate @JeromSar
