### ISSUE TITLE
Adding optional Reasons with /noob?

### ISSUE THREAD

**Issue by EXPLODINGTNT001** [TotalFreedom/TotalFreedomMod#775] opened 2015-08-07 21:59 UTC
We should add reasons with /noob because when we /noob someone, it just says they are tempbanned, and if they decide to make a ban appeal, (even though its 5 minutes) or if they think they were banned without reasons, they can know why they are banned if /noob had reasons.
Command syntax: /noob <player> [reason]

**Comment by jjkatz613** [comment] 2015-08-09 01:56
I vouch for this and would provide code. But where exactly is /noob in tfm.

**Comment by GangSterFlexx** [comment] 2015-08-09 11:41
In command section/folder

So, me.StevenLawson.TotalFreedomMod.Commands.Command_noob.java

**Comment by jjkatz613** [comment] 2015-08-09 12:09
@GangSterFlexx  It wasnt clear. I didnt find it in there.

**Comment by GangSterFlexx** [comment] 2015-08-09 12:11
Strange... Either it been deleted or something going wrong :/

**Comment by Wild1145** [comment] 2015-08-09 17:11
Its not designed to have a reason, just as a quick tempban for noobs. Maybe we just need to change the kick message?

**Comment by AlexFreedomMod** [comment] 2015-08-12 16:45
Vouch

**Comment by aggelosQQ** [comment] 2015-08-21 22:17
@jjkatz613 /noob is the /tban command, it's named tban on tf, and /noob is an aliase.

**Comment by JeromSar** [comment] 2015-10-12 06:47
Duplicate of #848

**Closed by JeromSar** 2015-10-12 06:47 UTC
Labels: Duplicate, Issue: Enhancement

**Comment by DUFCLiam** [comment] 2016-03-10 16:57
@JeromSar Your one would be duplicate so change the message please.
