### ISSUE TITLE
Persist tags

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#1547] opened 2016-03-09 23:31 UTC
Setting a /tag and then relogging will remove the tag, regardless of rank.
Since we already have the ability to clear all tags, there's no point of wiping it upon relog.

**Comment by JeromSar** [comment] 2016-03-10 14:30
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/208

**Closed by JeromSar** 2016-03-10 14:30 UTC

**Comment by ShadowArmadyl** [comment] 2016-03-14 03:39
@JeromSar - this is not a duplicate.

**Comment by AvalancheYT** [comment] 2016-03-14 04:32
@ShadowArmadyl, if you read carefully, it is a duplicate.
Same thing but different phases.

**Comment by ShadowArmadyl** [comment] 2016-03-14 13:18
@AvalancheYT, oops, sorry. I thought this was another issue.
