### ISSUE TITLE
/glist

### ISSUE THREAD

**Issue by AlphaGaming** [TotalFreedom/TotalFreedomMod#847] opened 2015-10-12 06:42 UTC
I have a thought of a command even though someone else made this and it got accepted but it look better and cleaner
"/command [banhistory] [today, lastweek, lastmonth] So if I wanted to use it I would do /glist banhistory today

User's you haved banned today: user1, user2, user3 and user4

**Comment by AlphaGaming** [comment] 2015-10-18 16:47
Bumpity bump bump

**Comment by Pluteno95** [comment] 2015-10-18 17:18
vouch

**Comment by mysteriace** [comment] 2015-10-18 17:29
vouch

**Comment by JeromSar** [comment] 2015-10-18 17:49
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/808

**Closed by JeromSar** 2015-10-18 17:49 UTC
Labels: Issue: Enhancement
