### ISSUE TITLE
PlayerCommandPreProcessEvent Error

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#607] opened 2015-05-11 21:36 UTC
:[21:35:17 INFO]: [PREPROCESS_COMMAND] Cheesy_Nuts(Cheesy_Nuts): /o why ban?
:[21:35:17 INFO]: [PLAYER_COMMAND] Cheesy_Nuts (Cheesy_Nuts): /o why ban?
:[21:35:17 INFO]: [TotalFreedomMod] [ADMIN] Cheesy_Nuts [STA]: why ban?
:[21:35:17 INFO]: Kevin6847 issued server command: /rl
:[21:35:17 INFO]: [PREPROCESS_COMMAND] Kevin6847( Name): /rl
:[21:35:17 ERROR]: Could not pass event PlayerCommandPreprocessEvent to TotalFreedomMod v4.3org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1131)
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Command cannot be empty
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321)
        at org.bukkit.event.player.PlayerCommandPreprocessEvent.setMessage(PlayerCommandPreprocessEvent.java:98)
        at me.StevenLawson.TotalFreedomMod.Listener.TFM_PlayerListener.onPlayerCommandPreprocess(TFM_PlayerListener.java:717)
        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)

**Comment by AlexFreedomMod** [comment] 2015-05-11 21:38
@xDestroyer217 So a op did /rl on TotalFreedom!??!??!?!

**Comment by xDestroyer217** [comment] 2015-05-11 21:54
It just breaks something, not reload.

**Comment by AlexFreedomMod** [comment] 2015-05-11 21:56
ooh
Thats why nothing unloaded

**Comment by AlexFreedomMod** [comment] 2015-05-11 21:57
- [X] Find what caused the issue
- [X] Report it on github!
- [X] Figure Out why it happend 
- [X] SAy it in the issue!


Caused by: java.lang.IllegalArgumentException: Command cannot be empty

**Comment by JeromSar** [comment] 2015-05-12 14:59
Fixed in https://github.com/TotalFreedom/TotalFreedomMod/commit/e2d0e9e75438178c1a3c5e9e7960f0a673fa6fc9
Thanks for the report!

**Closed by JeromSar** 2015-05-12 14:59 UTC
