### ISSUE TITLE
A way for an admin to permanently set their tag.

### ISSUE THREAD

**Issue by xAtomik** [TotalFreedom/TotalFreedomMod#2139] opened 2017-12-22 21:25 UTC
Admins usually have to set their tag every time they join if they use a custom one, and it can be annoying. Surely there could be a command which can do this? Something like **/myadmin settag <tag>** or something along those lines. It would really help admins out.

**Comment by Wild1145** [comment] 2017-12-24 14:07
Duplicate of #208

**Closed as completed by Wild1145** 2017-12-24 14:07 UTC
Labels: Duplicate, Issue: Enhancement
