### ISSUE TITLE
Enchancement Command Smite

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1521] opened 2016-03-07 20:09 UTC
/smite Player : Reason, will be more useful, without using /say , when you type /smite player testing

will say Player was a naught naught boy

Reason: Dont Fastbow near spawn etc...

**Comment by Adaptified** [comment] 2016-03-07 20:10
Duplicate

**Comment by JeromSar** [comment] 2016-03-07 20:10
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848

**Closed** 2016-03-07 20:11 UTC
Labels: Duplicate, Issue: Enhancement
