### ISSUE TITLE
Change gtfo.

### ISSUE THREAD

**Issue by OxLemonxO** [TotalFreedom/TotalFreedomMod#1456] opened 2016-01-19 11:02 UTC
Why don't we change gtfo to be like tempban so it tempbans for 24hours, so that mark doesn't have to clear the ban lists every day?

**Comment by Chaosiity** [comment] 2016-01-19 18:06
Great Idea.

**Comment by vladvilcu2006** [comment] 2016-01-19 22:38
vouch

**Comment by DUFCLiam** [comment] 2016-01-20 16:04
Vouch.

**Comment by Wild1145** [comment] 2016-01-20 16:12
Just tempban them for 24 hours... GTFO is designed as a longer term banning option rather than a tempban. Mark simply chooses to wipe the bans every 24 hours. GTFO bans are not "supposed" to be a 24 hour ban, rather a "You fucked up, you can be banned until we decide to unban you"

**Comment by DUFCLiam** [comment] 2016-01-20 16:13
I agree; Changed to Neutral until further discussion @markbyron

**Comment by Wild1145** [comment] 2016-01-20 16:15
@DUFCLiam Please do not "Vouch" or "Neutral" on Github... It adds nothing to the development process and just clutters up the comments.

**Comment by DUFCLiam** [comment] 2016-01-20 16:17
But, @Wild1145 I makes it easier to see if people like the implementation of this feature.

**Comment by Wild1145** [comment] 2016-01-20 20:44
@DUFCLiam Its of absolutely no use to the issue from a development stand point... It spams the comments like this discussion making it more time consuming when we come back to look at the way that implementation was discussed.

**Comment by xItsNickHD** [comment] 2016-01-25 03:02
Why? How long does it really ban them for?

**Comment by OxLemonxO** [comment] 2016-01-25 11:21
@xItsNickHD Forever, till mark clears the banlists

**Comment by xItsNickHD** [comment] 2016-01-25 11:39
@OxLemonxO, well what if mark is busy on the day and can't do it? Couldn't we set something in the host to run the command daily and purge the banlist?

**Comment by AvalancheYT** [comment] 2016-01-25 13:49
@xItsNickHD, we can always implement it in TFM.

**Comment by OxLemonxO** [comment] 2016-01-26 11:22
@xItsNickHD That's what this issue is for.

**Comment by Wild1145** [comment] 2016-01-27 23:34
GTFO is NOT a 24 hour tempban... That is not what it is designed for... This issue would change the fundamental functionality and design of the command... It is designed as a shorter term permban... Else you'd just tempban them...

**Comment by JeromSar** [comment] 2016-02-07 20:36
Since Mark wipes the bans every 24 hours anyway, I see no issue with letting the bans expire after 48 hours.

**Comment by JeromSar** [comment] 2016-02-07 20:37
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/806

**Closed by JeromSar** 2016-02-07 20:37 UTC
Labels: Issue: Enhancement
