### ISSUE TITLE
Mute Reasons / Timers

### ISSUE THREAD

**Issue by AlphaTZ** [TotalFreedom/TotalFreedomMod#768] opened 2015-08-01 18:19 UTC
For commands like mute we should have the option to put a reason in and set a timer. 
When you mute someone, it should announce the reason and when the user attempts to chat it'll tell them why and the amount of time left of the mute.

**Comment by jjkatz613** [comment] 2015-08-02 02:49
Vouch

**Comment by Elephants111** [comment] 2015-08-02 22:55
There have already mute in 5 mins like mute / freeze / etc from totalfreedom auto purge it.

**Comment by Elephants111** [comment] 2015-08-02 22:56
What if you mute them 10 mins then totalfreedom: unmute them.... then It's not work for that.

**Comment by tylerhyperHD** [comment] 2015-08-23 16:22
That can be possible with heartbeat involved.

**Comment by JeromSar** [comment] 2015-10-12 06:51
Duplicate of #848

**Closed by JeromSar** 2015-10-12 06:51 UTC
Labels: Issue: Enhancement

**Comment by DUFCLiam** [comment] 2016-03-10 16:59
Not a duplicate @JeromSar

**Comment by JeromSar** [comment] 2016-03-10 17:58
It must definitely is @DUFCLiam

**Comment by Wild1145** [comment] 2016-03-10 18:07
@JeromSar His point is that this is issue 768 and thats 848 being that #848 should be the duplicate.

**Comment by JeromSar** [comment] 2016-03-10 18:22
@Wild1145 While I understand where he's coming from, the word "duplicate" does not imply which issue came first.

**Comment by Wild1145** [comment] 2016-03-10 18:41
@JeromSar Yeah, I saw that you made that point on one of the later notifications. Thus why I didnt waste my time posting the same on every issue that he commented and you commented on.
