### ISSUE TITLE
How do you set your login message?

### ISSUE THREAD

**Issue by Cleinad119** [TotalFreedom/TotalFreedomMod#1725] opened 2016-05-17 19:52 UTC
Hello everyone. I need to set my login message. I cannot use /myadmin, because I am not able to compile the source code. How can I set my login message?

-Cleinad

**Comment by rovertdude** [comment] 2016-05-17 23:18
This is essentially a duplicate of your previous post, #1681

**Comment by Cleinad119** [comment] 2016-05-17 23:30
Actually, I am asking HOW I set my login. Not asking for the latest version.

**Comment by RobinGall2910** [comment] 2016-05-18 00:14
@Cleinad119 you actually answered your own question in that title, of #1681.

Though, it's `/myadmin setlogin (a) &6someone &band &ablah`

**Comment by Cleinad119** [comment] 2016-05-18 08:06
I said I cannot USE /myadmin setlogin. Someone told me I could use admins.yml. I am using 5.0 Pre-Rel 1 and /myadmin setlogin is not s command. Is there still a way to set my login message?

**Comment by JeromSar** [comment] 2016-05-19 19:50
@Cleinad119 Please ensure you have compiled and installed the latest version (on branch tfm50).

**Comment by Wild1145** [comment] 2016-08-19 16:59
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

**Closed by Wild1145** 2016-08-19 16:59 UTC
Labels: Issue: Help Wanted
