### ISSUE TITLE
Splash Potion Blocker, Kit clear command to counter death potions.

### ISSUE THREAD

**Issue by EXPLODINGTNT001** [TotalFreedom/TotalFreedomMod#772] opened 2015-08-04 19:28 UTC
As of recently, players have stored death potions in /kits and they seem to know which kits have the death pots because all the death pots have the same names, and the same killing capabilities, so as a counter to that, we should add a command to clear kits. As a counter to block splash potions, we should disable splash potions, and when someone attempts to use one, A message should pop up on the player's screen advising them, if they want to use potions, that they should use potions.

*Notify me if this is a duplicate*

**Comment by ValenciaOrange** [comment] 2015-08-05 01:03
I think the splash potion blocker would be useful, I did make a kit that contains admintools such as log stick, compass, wand..etc

**Comment by PattyToTheWatty** [comment] 2015-08-07 06:33
* As a counter to block splash potions, we should disable splash potions, and when someone attempts to use one, A message should pop up on the player's screen advising them, if they want to use potions, that they should use potions* Duplicate of my issue.

**Comment by GangSterFlexx** [comment] 2015-08-07 10:46
I was thinking maybe blocking Splash Event but don't block the drinkable ones.

**Comment by ValenciaOrange** [comment] 2015-08-07 18:02
#773

**Comment by EXPLODINGTNT001** [comment] 2015-08-07 21:37
I had code in a old TFM of mine that blocked potions, telling users to use /potion to set potion effects.I might re-implement it in my server, and modify it to work on splashers

**Comment by Wild1145** [comment] 2015-08-09 17:13
The splash potions of death thingies are a duplicate, but stopping potions being saved in kits is the new part.

**Comment by ValenciaOrange** [comment] 2015-08-13 14:28
@Wild1145 mark had already removed the kit adding plugin. Players can no longer create or edit kits

**Comment by Wild1145** [comment] 2015-08-21 22:29
@ValenciaOrange Depending on Essentials you may have been able to also save them into kits within essentials its self, I am however unsure if that is the case.

**Comment by ValenciaOrange** [comment] 2015-08-22 00:03
@Wild1145 you can only create or save kits by accessing server files and going into config.yml under the essential folder. Unless the server has plugins that does that for them. There is no command in game to edit kits.

**Comment by JeromSar** [comment] 2015-08-22 09:09
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/690

**Closed by JeromSar** 2015-08-22 09:09 UTC
Labels: Issue: Enhancement

**Comment by Elephants111** [comment] 2015-08-25 21:55
/give [username] potion 1 16385 {CustomPotionEffects:[{Id:6,Amplifier:253}]}
