### ISSUE TITLE
Adding /clearparticles

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#957] opened 2015-12-19 19:20 UTC
https://github.com/TotalFreedom/TotalFreedomMod/pull/949

I think it is an useful command

**Comment by JeromSar** [comment] 2015-12-20 12:01
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/944

**Closed by JeromSar** 2015-12-20 12:01 UTC
Labels: Issue: Enhancement
