### ISSUE TITLE
Owner should get all Permissions

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#653] opened 2015-05-19 09:44 UTC
Hello there. Im finding nearly everyone asks me Can you code me a mod? Can you code me some ranks? Im starting to find it really really annoying.
Can you please add Owner gets all the permissions.
People will mostly go to the config

Many thanks, IPatty

**Comment by Wild1145** [comment] 2015-05-19 10:48
"Owner" is not a rank... Its merely a display title. It doesn't and should not have any additional permissions. Just add the person to Senior Admin, and then add their username in the config file to owner. There you are, full permissions.

**Comment by JeromSar** [comment] 2015-05-21 19:30
Ranks are getting a revamp, owner will be a seperate rank now. Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/628

**Closed by JeromSar** 2015-05-21 19:30 UTC
Labels: Issue: Enhancement
