### ISSUE TITLE
Command suggestion: /glist banip <ip>

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#935] opened 2015-12-17 19:53 UTC
It should let use admins ban IP's in the event we find an IP but not username.

**Comment by Wild1145** [comment] 2015-12-18 00:30
I am 99% Certain this is a duplicate...

**Comment by ReelPattytothewatty** [comment] 2015-12-18 21:10
Yes, @Wild1145. It certainly is. This has been suggested before and denied.

**Comment by Wild1145** [comment] 2015-12-20 17:32
@ReelPattytothewatty No... The issue is already open... Its a good valid issue, but I believe its been duplicated.

**Comment by Wild1145** [comment] 2015-12-20 17:33
Confirmed. Duplicate of #871

**Closed** 2015-12-20 18:45 UTC
Labels: Duplicate, Issue: Enhancement
