### ISSUE TITLE
Schematic Manager - Broken?

### ISSUE THREAD

**Issue by VjGamingUK** [TotalFreedom/TotalFreedomMod#299] opened 2014-08-27 18:51 UTC
Is the Schematic Manager "Upload Section" http://tf.madgeekonline.com:28966/schematic/upload
link bugged? Whenever you try upload a schematic it'll say "Error uploading schematic" even if it's spelt right with the ".schematic" at the end.

**Comment by JeromSar** [comment] 2015-04-22 09:23
@StevenLawson Could you take a look?

**Comment by Wild1145** [comment] 2017-01-08 00:46
Can anyone confirm if this bug is still happening? I havent heard anything for some time that this has been an issue...

**Comment by aggelosQQ** [comment] 2017-01-09 18:18
@Wild1145 Just uploaded a schematic and it seems to be working.
The file is called testschemAgg.schematic

**Comment by Wild1145** [comment] 2017-01-09 18:29
In that case I will close this issue. If anyone can reproduce the issue in the future feel free to re-open it.

**Closed by Wild1145** 2017-01-09 18:29 UTC
Labels: Bug
