### ISSUE TITLE
Disallow opping already opped players

### ISSUE THREAD

**Issue by aggelosQQ** [TotalFreedom/TotalFreedomMod#887] opened 2015-11-05 18:38 UTC
To avoid the spam caused by trollers spamming /op, we should made a restriction to the /op command and not allow people OP players that are already opped.

I have this feature on my server: 
https://github.com/ImmaFreedom-Dev/ImmaFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_op.java#L59-#L66

**Comment by xItsNickHD** [comment] 2015-11-05 19:30
Sounds like a epic idea.

**Comment by Scribbles4321** [comment] 2015-11-05 19:33
Vouch

**Comment by OutOfYourMind** [comment] 2015-11-05 21:41
Apology, I didn't see the first pull request go through so I made a second.

**Comment by JeromSar** [comment] 2015-11-05 21:47
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/538

**Closed by JeromSar** 2015-11-05 21:47 UTC
Labels: Issue: Enhancement
