### ISSUE TITLE
Broadcasting the admins name while banning.

### ISSUE THREAD

**Issue by mgejay** [TotalFreedom/TotalFreedomMod#1966] opened 2017-01-31 00:14 UTC
Similar to gban or an offline ban, GTFO should broadcast the admin responsible for banning the user to evade confusion. If this is a duplicate, let me know please.

**Comment by Wild1145** [comment] 2017-01-31 22:41
Duplicate of #497

**Closed as completed by Wild1145** 2017-01-31 22:41 UTC
Labels: Duplicate, Issue: Enhancement
