### ISSUE TITLE
/chatcooldown

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#996] opened 2015-12-23 21:05 UTC
I think something like /chatcooldown could be good. It might be only be able to be used by Super Admin+. It would add a chat cooldown that maybe Super Admin+ only can bypass. It might be useful when people are spamming or chat chaos or if the server's being botted.

**Comment by Adamx120** [comment] 2015-12-23 21:12
Total'Freedom'

**Comment by ReelPattytothewatty** [comment] 2015-12-23 22:19
Thats why we have senior and telnet admins for?

**Comment by Wild1145** [comment] 2015-12-23 23:48
I think there should be the option to enforce a cooldown period. It would be handy when you are getting spambots, however TFM should auto kick them. I like the idea as an administrative tool that can be toggled for short amounts of time as necessary.

**Comment by OnlineRepz** [comment] 2015-12-24 00:32
I am pretty sure that this is a duplicate.

**Comment by DUFCLiam** [comment] 2015-12-24 09:09
Duplicate of #677

**Comment by JeromSar** [comment] 2015-12-25 09:57
Also of https://github.com/TotalFreedom/TotalFreedomMod/issues/798

**Closed by JeromSar** 2015-12-25 09:57 UTC
Labels: Issue: Enhancement
