### ISSUE TITLE
Muted players can PM?

### ISSUE THREAD

**Issue by aggelosQQ** [TotalFreedom/TotalFreedomMod#405] opened 2015-01-12 15:35 UTC
![](https://www.screenshottr.us/v/1f955de0ac231486b27e11d7b81e3723/e2707fbabd1a907cddd4703c44d73346.png)

![](https://www.screenshottr.us/v/21ac0b35f2d8134387dc90b805a411bc/744eec58ab01bd30ed1f1611aebc270b.png)

![](https://www.screenshottr.us/v/7222f3749071a30769bab8158e85d5c1/21e24c1db12d1581c2510f7df16068bc.png)

![](https://www.screenshottr.us/v/486d4cc78ecf57615ec4fed35de60ad9/641bd5a5c97515d2cdf8d145e9d31cbd.png)

I thought muted players couldn't use any communicative command such as /msg, /me and etc..

**Comment by notchface72** [comment] 2015-01-12 15:37
OFT: Hehe, muted players can mute.
ONT: Nither did I. That's weird.

**Comment by aggelosQQ** [comment] 2015-01-12 15:38
Fixed :P

**Comment by Robolawrence** [comment] 2015-01-13 05:17
so they're not supposed to be able to pm whilst muted? Never thought they weren't.

**Comment by Wild1145** [comment] 2015-01-15 09:12
What was the actual command they used to send that message?

**Comment by aggelosQQ** [comment] 2015-01-15 22:48
I didn't notice.

**Comment by Wild1145** [comment] 2015-01-15 22:57
Maybe its worth just blocking all commands for muted players?

**Comment by WickedGamingUK** [comment] 2015-01-22 12:48
@Wild1145 That's a bit OTT. The best way probably would be to have a listener for when someone sends a command, if that command is in the list of commands that muted players cannot use and the player is muted it'll will send a player a message then cancel the event.

**Comment by Wild1145** [comment] 2015-01-22 13:07
That's what is or was at least already in place. Due to aliasing and such
its easy enough to work around as a player

**Comment by JeromSar** [comment] 2015-04-26 23:03
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/312

**Closed by JeromSar** 2015-04-26 23:03 UTC
Labels: Bug
