### ISSUE TITLE
Allow custom "wall-of-text" messages with a single command backed by a YAML config

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2108] opened 2017-08-14 09:16 UTC
So for commands like /ai /verify and the PR for /savebuild they are purely text based so what I am suggesting is this: We implement an engine of sorts that allows you to create custom text based commands that can be edited in config. So if you want a command like /ai you can specify this in the config and make it msg the user with the text. Thoughts?

**Comment by LiamTownsley** [comment] 2017-08-14 09:48
Can you explain more?

**Comment by ghost** [comment] 2017-08-14 10:08
As in, instead of hard coding command just to display text you have a specific config file where you can specify commands, i.e.
commands:
     ai:
        - Eat your brugers and fries 
        - Visit the pasta factory
     verify:
        - the admins are coming for you!

Then those commands would be loaded and the given lines displayed when said command is run

**Comment by untuned** [comment] 2017-08-14 18:21
customcommands.yml
```
commands:
  ai:
  - hello
  - bye
  verify:
  - ok
  - cool
```

**Comment by Mafrans** [comment] 2017-08-15 02:12
could be done quite easily

**Comment by JeromSar** [comment] 2017-08-15 18:18
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/317

**Closed as completed by JeromSar** 2017-08-15 18:19 UTC
Labels: Duplicate, Issue: Enhancement
