### ISSUE TITLE
tban/noob with reasons

### ISSUE THREAD

**Issue by TheCool1Mike** [TotalFreedom/TotalFreedomMod#1549] opened 2016-03-11 10:34 UTC
I wish to add the ability to tban/noob with reasons. This will make it much faster to tempban people for five minutes. By comparison, /tban Mike Minor griefing is much easier than doing /tempban Mike 5m Minor griefing

**Comment by AvalancheYT** [comment] 2016-03-11 11:01
@TheCool1Mike, this is already added TFM 5.0 unless I missed something.

**Comment by TheCool1Mike** [comment] 2016-03-11 11:14
@AvalancheYT It's not, it doesn't actually work.

**Comment by Wild1145** [comment] 2016-03-11 12:11
Its not supposed to, /tban and /noob are designed as very quick commands to ban someone for 5mins, if you want to ban someone with a reason use /tempban  (/tempban <user> <time> <Reason>) Done.

**Comment by DUFCLiam** [comment] 2016-03-12 15:56
I have to agree with @Wild1145

**Comment by JeromSar** [comment] 2016-03-15 17:02
Duplicate of #848

**Closed by JeromSar** 2016-03-15 17:02 UTC
Labels: Issue: Enhancement
