### ISSUE TITLE
Spam bots

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#885] opened 2015-11-04 01:04 UTC
I suggest making the anti spam class react quicker.

**Comment by LifeAsStranger** [comment] 2015-11-04 05:58
Duplicate to one of the issues.

**Comment by JeromSar** [comment] 2015-11-04 12:30
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/798

**Closed by JeromSar** 2015-11-04 12:30 UTC
