### ISSUE TITLE
Limit /tpo and /tpohere to admin

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#797] opened 2015-08-23 14:35 UTC
/tpo and /tpohere are identical to /tp and /tphere except that the o is override, and bypasses tptoggle. IMO only admins should be able to bypass someone's teleport setting. 

Mark seems to agree also:
http://totalfreedom.boards.net/post/302169

**Comment by tylerhyperHD** [comment] 2015-08-23 15:11
Since teleporting others is against the rules, this needs to be dealt with, either by making /tpo and /tpohere blocked or making them the same as /tp and /tphere

**Comment by ValenciaOrange** [comment] 2015-08-24 00:31
If someone had they tp disabled, they mean they do not want to be disturbed. However, the op can still use /coords (Valencia_Orange) then /tppos

**Comment by aggelosQQ** [comment] 2015-08-30 11:18
You can still tp others to you using /tp <name> <yourname>

**Comment by LegendIsAwesomes** [comment] 2015-08-30 14:02
@aggelosQQ If it is blocked for SA only, ops could do /tptoggle so ops can't TP to others when they have tptoggle on.

**Comment by aggelosQQ** [comment] 2015-08-30 20:40
Yep, but I object to this suggest as it is not a big deal, plus, it will reduce the freedom of the server.

**Comment by JeromSar** [comment] 2015-12-28 13:52
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/713

**Closed by JeromSar** 2015-12-28 13:52 UTC
Labels: Issue: Enhancement
