### ISSUE TITLE
Offline /tempban

### ISSUE THREAD

**Issue by SixtyFourWarrior** [TotalFreedom/TotalFreedomMod#967] opened 2015-12-20 16:19 UTC
I'd suggest this because some players breaking Section 3 rules. Like they are spamming advertise a lot  and they quit. So admins think "I must do /glist ban". And they do it. But when Section 3 rules broke, they must be banned several mins but with /glist, we banning them a day. So I think /tempban needs to ban offline players like /glist.

**Comment by DUFCLiam** [comment] 2015-12-20 16:25
I agree with the "/glist ban <Username>" because they left to bypass a ban.

**Comment by Wild1145** [comment] 2015-12-20 17:30
Yeah... If they left the odds are they knew they were about to get banned and either wouldnt come back anyway, or deserve the longer ban due to the fact they left purposely to avoid getting a 10min temp ban or something.

**Comment by vladvilcu2006** [comment] 2015-12-20 23:33
@Wild1145  5min*

**Comment by Wild1145** [comment] 2015-12-21 11:44
@vladvilcu2006 Not really important...

**Comment by JeromSar** [comment] 2015-12-28 13:42
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/298

**Closed by JeromSar** 2015-12-28 13:42 UTC
Labels: Issue: Enhancement
