### ISSUE TITLE
GTFO putting names

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#398] opened 2015-01-10 13:16 UTC
When you GTFO someone why not make it so when you GTFO someone it automatically puts your name at the end of the gtfo message. It will solve the problem of people not knowing who banned them in there ban appeals so they can put there names and can say why they banned whoever. Here is a example of the message. 

GTFO 
Grief (No name)

My idea.

GTFO
Grief (Username)

**Comment by Wild1145** [comment] 2015-01-10 13:22
Duplicate of #350

**Comment by LegendIsAwesomes** [comment] 2015-01-10 13:25
Oh, didnt see.

**Closed** 2015-01-10 15:58 UTC
Labels: duplicate
