### ISSUE TITLE
Block /fill

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#696] opened 2015-06-09 20:53 UTC
Anyone that has admin access to TotalFreedom can see the perm-ban request I sent in here:

http://totalfreedom.boards.net/thread/24202/new-crash

Basically, you can bypass all filters and place blocks such as that everywhere, that lag because of particle spam, portal spam, etc.

**Comment by JeromSar** [comment] 2015-06-11 08:17
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/634

**Closed by JeromSar** 2015-06-11 08:17 UTC
