### ISSUE TITLE
Tag clean (/tc)

### ISSUE THREAD

**Issue by Decyj145** [TotalFreedom/TotalFreedomMod#1963] opened 2017-01-24 16:14 UTC
We have /nc, and i was wondering if we could do /tc (tagclean) as the same colour codes, like it cleans &k, &0, etc.

I was wondering if it would come in handy.

**Comment by ExactObject** [comment] 2017-01-24 16:20
sounds good to me.

**Comment by Wild1145** [comment] 2017-01-24 19:16
Duplicate of #725

**Closed as completed by Wild1145** 2017-01-24 19:16 UTC
Labels: Duplicate, Issue: Enhancement
