### ISSUE TITLE
How to stop DeathPotions (Maybe)

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#918] opened 2015-12-11 23:06 UTC
You can maybe block items being spawned in as "KillerPotion" or "TrollPotion"

**Comment by JeromSar** [comment] 2015-12-12 13:47
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/690

**Closed by JeromSar** 2015-12-12 13:47 UTC
Labels: Issue: Enhancement

**Comment by DUFCLiam** [comment] 2015-12-13 11:32
No, This is not a Duplicate as I am wanting to block the spawning of KillerPotions and TrollPotions they where saying to heal on join.

**Comment by JeromSar** [comment] 2015-12-13 12:01
@DUFCLiam This is a duplicate because the issue (cause) is the same. Whether the solution to that problem is different is irrelevant.

**Comment by DUFCLiam** [comment] 2015-12-13 12:04
Ok, And can you make a Video on how to Compile TFM please.

**Comment by Wild1145** [comment] 2015-12-15 13:11
@DUFCLiam There are about a million tutorials on how to compile TFM. If you are unable to compile it on your own then you probably should stick to using just the releases as compiling is a fairly simple step in the Java Language.
