### ISSUE TITLE
Blocking Creative PvP

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1910] opened 2016-11-13 17:22 UTC
So, in order to reduce the headache with hunting godmode and creative PvP'ers, I came up with this. 
If a player is in creative mode, and they hit another player in survival, it will not do any damage. However, I can type a command (ex. /cpvp) and people can hit me in creative mode if I want them to test out weapons etc. If someone does hit them in creative and /cpvp isn't enabled for that player, they will be auto-warned.

**Comment by JeromSar** [comment] 2016-11-13 17:23
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/287. Raise your suggestions as a comment on that issue.

**Closed as completed by JeromSar** 2016-11-13 17:23 UTC
Labels: Duplicate, Issue: Enhancement
