### ISSUE TITLE
Add a set tag

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2143] opened 2017-12-28 21:10 UTC
"This will hopefully clear up the "STA/TCA" issue.

I am asking for a new command for admins, namely /myadmin settag <tag>.  This is helpful if you want specific colors for your tag, or you're a TCA and not a STA.

It will automatically apply on join, so you will not need to apply it manually every time."
http://totalfreedom.boards.net/thread/57077/myadmin-settag

**Comment by Wild1145** [comment] 2017-12-28 21:15
TFM does not see TCA as a rank. This is also a duplicate of about 50 other issues if I get what you're asking for, which is persistent tags. I cant be bothered tagging it because I do it just about every other issue currently.

**Closed as completed by Wild1145** 2017-12-28 21:15 UTC
Labels: Duplicate, Issue: Enhancement
