### ISSUE TITLE
Censor IPs

### ISSUE THREAD

**Issue by xItsNickHD** [TotalFreedom/TotalFreedomMod#1889] opened 2016-10-19 07:32 UTC
http://totalfreedom.boards.net/thread/46329/censor-ips

**Comment by ghost** [comment] 2016-10-19 08:30
The fact I can't actually read this post is a big disappointing put from the title I can guess its a duplicate of the ip censoring in /glist ban. This is not hard to implement and unlike Wild's 'ips are free info' point of view, I believe that we should not take the risk of broadcasting player's ips where any ddoser can get them.

**Comment by ghost** [comment] 2016-10-19 09:03
I did the glist patch, @JeromSar need to accept it
#1822

**Comment by mayokek** [comment] 2016-10-19 10:03
IP addresses are a public information.

**Comment by ghost** [comment] 2016-10-19 10:18
@AvalancheYT is not!
http://www.out-law.com/page-8060

**Comment by lemonsked** [comment] 2016-10-19 13:40
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/1853.

**Closed as completed by lemonsked** 2016-10-19 13:40 UTC
Labels: Duplicate, Issue: Enhancement, Issue: Declined
