### ISSUE TITLE
Add a "Master Builder" Rank for OPs and Admins

### ISSUE THREAD

**Issue by Cleinad119** [TotalFreedom/TotalFreedomMod#1802] opened 2016-08-01 01:32 UTC
I was thinking of adding two versions of the Master Builder Rank.
One of them would be given to OP's (We don't want OP's running around acting like Admins just because they are a Master Builder), and the other would be for Admins. I guess we could have the MB rank for admins be like:

OP MB - Login Message, Title
Admin (SA): Title, Login Message, normal SA Permissions
Admin (STA): Title, Login Message, normal STA Permissions
Admin (SrA): Title, Login Message, normal SrA Permissions

I can whip this up as my first contribution if you would like. :)

**Comment by robingall2910** [comment] 2016-08-01 02:43
`we don't want ops running around acting like admins just because they are a master builder` then admins should have the permissions, or at least seniors to temp remove the role/rank, and re add it back. we hardly have any master builders as ops, and they're well known if they're ops right now on tf.

**Comment by Wild1145** [comment] 2016-08-03 23:50
Master builder should be a title with minimal additional permissions and not a rank of its own.

**Comment by jjkatz** [comment] 2016-08-11 22:52
This is practically a duplicate of #1798

**Closed** 2016-08-13 14:16 UTC
Labels: Duplicate, Issue: Enhancement
