### ISSUE TITLE
/title

### ISSUE THREAD

**Issue by BlooStar** [TotalFreedom/TotalFreedomMod#649] opened 2015-05-17 20:28 UTC
/title if used correctly can make other people's clients crash. It also can be used to troll other players. Could we block /title?

**Comment by zD12** [comment] 2015-05-17 20:29
It's not an issue.  See #646

**Comment by Wild1145** [comment] 2015-05-17 20:29
Duplicate of #648 and #646

**Comment by BlooStar** [comment] 2015-05-17 20:33
Operator's are able to perform the command...

**Comment by Wild1145** [comment] 2015-05-17 20:44
I am aware. Its still a duplicate issue of #648 and #646

**Closed** 2015-05-21 19:31 UTC
Labels: Duplicate, Issue: Enhancement
