### ISSUE TITLE
/logs clear

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1864] opened 2016-09-11 20:40 UTC
Would there be a way to add a /logs clear (possibly only senior console or similar) to clear the logviewer access list?
Could help if someone has logviewer access and anyone removed can just do /logs again

**Comment by JeromSar** [comment] 2016-10-02 21:06
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/1852

**Closed as completed by JeromSar** 2016-10-02 21:06 UTC
Labels: Duplicate, Issue: Enhancement
