### ISSUE TITLE
CmdSpy upgrade

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1978] opened 2017-03-06 09:55 UTC
Issue to add in per rank cmdspy for staff.
i.e. Super can see op commands
Telnet can see op and Super commands
Senior can see Telnet and Super commands

**Comment by ghost** [comment] 2017-03-06 16:41
is a little buggy, the monitoring is not showing all Commands.

**Comment by Wild1145** [comment] 2017-03-06 18:42
Duplicate of #1830

**Closed as completed by Wild1145** 2017-03-06 18:42 UTC
Labels: Duplicate, Issue: Enhancement
