### ISSUE TITLE
add /ipban for offlinebans (impersonation)

### ISSUE THREAD

**Issue by notanoperator** [TotalFreedom/TotalFreedomMod#1828] opened 2016-08-18 11:52 UTC
We should add /ipban to ban online, and offline ips. Why? Let's say an administrator get's impersonated, and a noob super decides to gtfo that person. GTFO also namebans, so the admin can't rejoin off another ip, but with this, we can /seen fakeadmin and IP ban them. Also, "Why not just use /gadmin". Two reasons. 
1. Gadmin can get confusing, and by the time you find the target hash in the list of the others, the person already has left.
2. Gadmin is for online players only.
Opinions?

**Comment by Cleinad119** [comment] 2016-08-18 11:53
I like it.

**Comment by Wild1145** [comment] 2016-08-19 14:08
Maybe we need to look at re-working the GAdmin system?

**Comment by marcocorriero** [comment] 2016-08-19 15:28
make /gadmin features as /glist features @Wild1145

**Comment by Wild1145** [comment] 2016-08-19 17:02
Duplicate of #289

**Closed by Wild1145** 2016-08-19 17:02 UTC
Labels: Duplicate, Issue: Enhancement
