### ISSUE TITLE
IP's shown when banned

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1893] opened 2016-10-30 08:11 UTC
I know issues about this have been made before but this time I cannot stress how important this issue is, I for the sanity of everyone I hope it gets fastracked and fixed pretty quick. First the issue: IP's showing when someone is banned, e.g. Gupta has been a very naughty boy, Banning ips 10.10.10.10
I know some think ips are public info and this shouldn't be rectified. I have seen reports and been able to test various clients that install ransomware on a person's PC, all they need is an IP and away they go. True hackers may be able to get ips different ways but the LEAST we can do to the players of TotalFreedom is to mitigate their potential exposure to DDOS and virus. I plead with either Wild or Jerom to fix this quick smart. Comments are welcome. This is not just a security member, but a courtesy and I hate for the server and the people that play their find out the hard way.

**Comment by mayokek** [comment] 2016-10-30 10:01
There is many issues that is similar to this and have been denied continuously. As @Wild1145 has stated in previous issues, IP addresses are a public information which don't need to be censored. If you are concern about your security, get a VPN to hide your public IP.

**Comment by ghost** [comment] 2016-10-30 10:12
AvalancheYT Wild can be wrong about things, this being one about them. You can't expect everyone to get VPN's just so they don't get DDOSed or get a virus. IPs are not THAT public. The inclusion of ips in banning is blatantly stupid and if Wild does not approve this then he is stupid to. tbh I am kinda sick of ideas that could actually help the server getting shot down by devs that don't think it should be added or noobs who know nothing about what is actually being suggested. Showing someones ip is downright dangerous. Full stop.

**Comment by mayokek** [comment] 2016-10-30 10:15
@Commodore64x, if you actually read the information about IP addresses, it is a public information.
Banning players which shows IP address can sometimes help us admins to find if the player is an impostor or not.

**Comment by ghost** [comment] 2016-10-30 10:17
AvalancheYT or you could just use /findip and stop endangering the players of the server by your laziness.

**Comment by mayokek** [comment] 2016-10-30 10:55
@Commodore64x, I believe you have misunderstood my statement. I meant if someone was breaking the rules, we can ban them and it will help us find if that person was imposed.

**Comment by JeromSar** [comment] 2016-10-30 11:52
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/1853

**Closed as completed by JeromSar** 2016-10-30 11:52 UTC
Labels: Duplicate, Issue: Enhancement
