### ISSUE TITLE
/findip Improvement

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#503] opened 2015-03-15 03:12 UTC
I was thinking that instead of it getting an online player's IP, it gets that player's IPs (whole IP list) from their player-data file.

If there is an alternative already implemented, please state and close ;)

**Comment by xDestroyer217** [comment] 2015-03-15 05:27
Hey hockey, from right now, I dont see there's an alt implemented, and I do like this to implement.

**Comment by JeromSar** [comment] 2016-02-07 20:41
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/437

**Closed by JeromSar** 2016-02-07 20:41 UTC
Labels: Issue: Enhancement
