### ISSUE TITLE
Change /stop system.

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1008] opened 2015-12-25 16:12 UTC
Hello, I am here again trying to get his accepted so lets get started

I would like to change the `/stop` ban system as it bans people who are testing commands or people do `/me Do /stop to stop lag!` as of this people try it that are
lagging so I am wanting to change it so it smites them and kicks them.

PR: {WAITING FOR ISSUE TO BE ACCEPTED}

**Comment by ReelPattytothewatty** [comment] 2015-12-25 20:45
Same as /rl, people say do /rl for rocketlauncher and then they get banned for a minute or so. This should just change the ban and the kick. When command is executed it should be: You cannot use this command!

**Comment by xDestroyer217** [comment] 2015-12-26 07:23
This really shouldn't just be touched at all.

**Comment by JeromSar** [comment] 2015-12-27 14:45
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/315

**Closed by JeromSar** 2015-12-27 14:45 UTC
