### ISSUE TITLE
Wurst Log Spammer issue (Crashes the server)

### ISSUE THREAD

**Issue by GX2H912** [TotalFreedom/TotalFreedomMod#1737] opened 2016-05-21 23:49 UTC
Can You possibly fix this from Wurst's new log spammer feature enabled logs in:

:[18:10:06 INFO]: UUID of player _6EQUJ5_ is fcf2772d-5747-4ef5-b266-960e8288f951
:[18:10:06 INFO]: _6EQUJ5_[/174.29.145.189:58476] logged in with entity id 8799 at ([flatlands]-498.57462491204285, 50.0, -799.7406826313044)
:[18:10:08 ERROR]: Couldn't select tradejava.lang.IndexOutOfBoundsException
at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470)
at net.minecraft.server.v1_9_R1.PacketDataSerializer.readInt(PacketDataSerializer.java:601)
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2239)
at net.minecraft.server.v1_9_R1.PacketPlayInCustomPayload.a(SourceFile:58)
at net.minecraft.server.v1_9_R1.PacketPlayInCustomPayload.a(SourceFile:8)
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
at java.lang.Thread.run(Thread.java:745)

**Comment by rovertdude** [comment] 2016-05-22 00:07
essentially a duplicate of #1736

**Comment by AvalancheYT** [comment] 2016-05-22 00:14
Next time, put it in pastebin. TBH, that is spamming as s**t

**Comment by DUFCLiam** [comment] 2016-05-22 10:27
This is a duplicate.

**Comment by JeromSar** [comment] 2016-05-22 13:59
@GX2H912 First of all, please do not post huge log entries on Github. Use pastebin!

This issue is a duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/1736

**Closed by JeromSar** 2016-05-22 13:59 UTC
