### ISSUE TITLE
Tags dissapear when plugin reloads (or server)

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1932] opened 2016-12-03 07:46 UTC
The title kind of says it all, and I am apprehensive of how to fix this. Any thoughts?

**Comment by mayokek** [comment] 2016-12-03 07:57
It's because the tags are not persistent

**Comment by ghost** [comment] 2016-12-03 08:00
I know WHY is happens but I am not sure of how to fix this.

**Comment by mayokek** [comment] 2016-12-03 08:04
You know the player data folder full with players configuration? We can save the tags there...

**Comment by ghost** [comment] 2016-12-03 08:06
Its not a matter of saving tags, its about reloading the tag manager when the server reloads

**Comment by mayokek** [comment] 2016-12-03 08:07
We can still save the tags onto the player's configuration, so when the server reloads, it won't remove the tag

**Comment by ghost** [comment] 2016-12-03 08:07
True, that would be one way, I will try to do it now.

**Comment by ghost** [comment] 2016-12-03 08:09
Actually this is a 1 line code change, a simple for loop that gets all players and their tags then sets them after the reload

**Comment by mayokek** [comment] 2016-12-03 08:12
I don't believe it would be quick enough to collect all of the players' tag before the reload occurs.

**Comment by ghost** [comment] 2016-12-03 08:21
Ok so I have found a solution. When the the TFM reloads (/tfm reload) it stops all services then starts them again. It finds all the services (of which ChatManager is one) and executes their onEnable methods. If something that loads tags can be put in there it will be fixed

**Comment by ghost** [comment] 2016-12-03 08:24
Creating a new method that grabs the tags of every online player and sets them which can be called in the onEnable method should do the trick

**Comment by ghost** [comment] 2016-12-03 08:26
8 lines of changed code and we are up and running!

**Comment by ghost** [comment] 2016-12-03 08:29
Oh fuck, I just found another issue with the same purpose from 2014...

**Comment by Wild1145** [comment] 2016-12-04 19:28
Duplicate of #208

**Closed as completed by Wild1145** 2016-12-04 19:28 UTC
Labels: Duplicate, Issue: Enhancement
