### ISSUE TITLE
Opme

### ISSUE THREAD

**Issue by ValenciaOrange** [TotalFreedom/TotalFreedomMod#508] opened 2015-03-20 19:33 UTC
For https://github.com/TotalFreedom/TotalFreedomMod/pull/502

The Command /opme is kinda useless,
1. Its only open to admins
2. Admins could just do /op (their username)

I made it so every players could use it but not Impostor. Players can just use /opme when they join instead of yelling in the chat or having the admins do /opall everytime.
I think this would make things a lot easier.

Changes:
The Command /opme was only open to admins, which is kinda unfair.
I updated the command /opme so when a new player joins or a player comes back from griefing..etc they can op them self rather them screaming and yelling in the chat "OP ME!, OP pls" or having the admins do /opall everytime when a new player joins.

I blocked the command to Imposter so when a Imposter try to use /opme they will not get op, but de-opped if they aren't de-opped already.

**Comment by zD12** [comment] 2015-03-20 20:10
@looperXD this command was created previous when we still used the command '/deopall'.  This remains as utterly useless, however, still remains as a custom command that older administrators, such as myself.  It should be noted, you could have commented on that pull request instead of actually creating a new issue.

**Comment by Wild1145** [comment] 2015-03-20 20:24
@zD12 Is there an issue for this already open or has it just been talked about in a separate PR?

**Comment by JeromSar** [comment] 2015-03-20 22:40
@looperXD /opme serves of historical value, it won't be removed. Is that what you were suggesting?

Please elaborate on what you're actually suggesting here.

**Comment by looperXD** [comment] 2015-03-20 22:41
I don't mean to remove it. I mean to Improve it 
https://github.com/TotalFreedom/TotalFreedomMod/pull/502

**Comment by JeromSar** [comment] 2015-03-20 23:01
@looperXD Please edit this issue and describe your changes.

**Comment by looperXD** [comment] 2015-03-20 23:14
Changes:
The Command /opme was only open to admins, which is kinda unfair.
I updated the command /opme so when a new player joins or a player comes back from griefing..etc they can op them self rather them screaming and yelling in the chat "OP ME!, OP pls" or having the admins do /opall everytime when a new player joins.

I blocked the command to Imposter so when a Imposter try to use /opme they will not get op, but de-opped if they aren't de-opped already.

**Comment by StevenLawson** [comment] 2015-03-20 23:16
Fun fact: /opme was TFMs first command.

**Comment by looperXD** [comment] 2015-03-20 23:18
Interesting, I thought it was opall XD

**Comment by Wild1145** [comment] 2015-03-20 23:32
Could we have some way of limiting this to one command execution per "reload" almost, that way if you get deopped for worledit stuff you cant just reop yourself and go again?

**Comment by Explosives** [comment] 2015-03-21 23:13
I like it because it's easier to type than "/op Explosives"

**Comment by ValenciaOrange** [comment] 2015-09-08 14:45
I think I might close this because theres no progress so far..... :-1:  :cry:

**Comment by JeromSar** [comment] 2015-09-08 16:32
@ValenciaOrange Don't close issues because there's no progress... However, as I said, I'd like to see your proposed changes in your original issue comment. Please edit your original message accordingly. :)

**Comment by Wild1145** [comment] 2016-08-19 18:26
This issue has been superseded by / is a duplicate of #340

**Closed by Wild1145** 2016-08-19 18:26 UTC
Labels: Duplicate, Issue: Enhancement
