### ISSUE TITLE
/cake

### ISSUE THREAD

**Issue by SamD22323** [TotalFreedom/TotalFreedomMod#2158] opened 2018-04-06 17:40 UTC
I have replaced Achievements with Advancements for /cake. the version has changed. what do i do for BAKED_CAKE. There is an error there

**Comment by Wild1145** [comment] 2018-04-07 21:19
Mojang changed how achievements work so it is a confirmed bug we are aware of.

**Comment by Wild1145** [comment] 2018-05-20 14:48
Duplicate of #2121

**Closed as completed by Wild1145** 2018-05-20 14:48 UTC
Labels: Issue: Bug, Duplicate, Issue: Bug Confirmed
