### ISSUE TITLE
Death potions are a problem

### ISSUE THREAD

**Issue by JacobMathBoy** [TotalFreedom/TotalFreedomMod#1647] opened 2016-05-10 23:26 UTC
I think that disallowing PlayerDeathEvents in creative might work.
```java
@EventHandler(priority=EventPriority.HIGHEST)
public void onDeath(PlayerDeathEvent evt) { // remove this code snippet if it's not okay to put code in issue text
    if (evt.getPlayer().getGameMode().equals(GameMode.CREATIVE)) {
        evt.setCancelled(true);
    }
}
```

**Comment by rovertdude** [comment] 2016-05-11 00:56
This should be in Pull Requests, not Issues.
Disabling deaths in creative will also stop most of /smite's

**Comment by JeromSar** [comment] 2016-05-11 09:20
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/690

**Closed by JeromSar** 2016-05-11 09:20 UTC
Labels: Issue: Enhancement
