### ISSUE TITLE
OPs with long tags, or tags with &k, &o, etc

### ISSUE THREAD

**Issue by EXPLODINGTNT001** [TotalFreedom/TotalFreedomMod#755] opened 2015-07-17 16:27 UTC
we should make these commands to manage the OPs with tags with banned characters like &k in them because when a OP puts a tag with &k on, the admins usually do /nickclean (/nc) but it does not clean tags. These suggestions might be helpful and it can prevent OPs from putting troll tags.
/detag - which takes everyone's tags off.
/tagclean (/tc) which is the same as /nickclean (/nc), but it cleans the tags and shows who had the tags.

**Comment by Wild1145** [comment] 2015-07-17 17:49
Duplicate.

**Comment by PattyToTheWatty** [comment] 2015-07-17 22:46
*duplicate* Next time maybe have a read through the issue enachement lists :)

**Comment by JeromSar** [comment] 2015-12-28 13:50
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/725

**Closed by JeromSar** 2015-12-28 13:50 UTC
Labels: Issue: Enhancement
