### ISSUE TITLE
/wipebans

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#965] opened 2015-12-20 12:33 UTC
Daily ban wipe that markbyron do daily.

Wiping:
- IP Bans
- UUID Bans

**Comment by Adamx120** [comment] 2015-12-20 12:40
Duplicate?

**Comment by JeromSar** [comment] 2015-12-20 12:40
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/806

Before you make any more issues, PRs or make any more comments, I insist you read the [Contributing Guidelines](https://github.com/TotalFreedom/TotalFreedomMod/blob/master/CONTRIBUTING.md).

**Closed by JeromSar** 2015-12-20 12:40 UTC
Labels: Duplicate, Issue: Enhancement
