### ISSUE TITLE
Knowing who banned you

### ISSUE THREAD

**Issue by ImScoop** [TotalFreedom/TotalFreedomMod#1448] opened 2016-01-12 22:21 UTC
Making an automated message in the GTFO message would be nice, and easier so we do not need to write our name manually after the reason.

**Comment by PacksGamingHD** [comment] 2016-01-13 04:17
i don't see a problem with it and its easy to implement

**Comment by Chaosiity** [comment] 2016-01-13 11:01
@PacksGamingHD I can easily do this, it just depends.

@JeromSar would you want something like:

"GTFO, Banned by <adminname>
Reason: <reason>"

or

"GTFO
reason: <reason> - <adminname>"

**Comment by PacksGamingHD** [comment] 2016-01-13 16:11
I was thinking it would be
GTFO
Reason: griefing (PacksGamingHD)
and if there's no reason
GTFO
Banned by: PacksGamingHD

**Comment by RobinGall2910** [comment] 2016-01-13 16:26
What if I don't want to show my name on it, there should be like an extra switch on to not show your name without a reason or something along those lines

**Comment by LegendIsAwesomes** [comment] 2016-01-13 17:08
This has already been done, and the PR is ready to merge since I made the PR.

**Comment by DUFCLiam** [comment] 2016-01-13 17:20
Duplicate of #946

**Comment by Sabermc7** [comment] 2016-01-14 16:58
Not important... including your username is optional it's just that most admins include it, it's the ban reason that's the most important as the op needs to know why they were banned.

**Comment by RobinGall2910** [comment] 2016-01-16 16:55
I agree with @Sabermc7. I'd rather not my name anyways in my ban reasons. It's a bit time consuming once from the start, and probably the player gets away most of the times if you keep typing long messages.

**Comment by xItsNickHD** [comment] 2016-01-25 03:13
Well it is already in tempbans, it couldn't be too complicated to copy it into a gtfo, and it should be because it's in a policy that they need a name to know who banned them to appeal.

**Comment by JeromSar** [comment] 2016-01-25 10:56
As @DUFCLiam pointed out, this has been implemented in TFM 5.0

**Closed by JeromSar** 2016-01-25 10:56 UTC
Labels: Issue: Enhancement
