### ISSUE TITLE
Reasons

### ISSUE THREAD

**Issue by gomalley411** [TotalFreedom/TotalFreedomMod#521] opened 2015-03-28 03:50 UTC
Self explanatory, but I'll explain it anyway. We should add reasons to /glist ban because, to put it simply, what if an OP finds that (s)he's banned but there's no reason listed? Wouldn't they be a bit angry about it? I sure would, and if we add reasons to /glist ban, we can tell the OP why they were banned if they don't already know. Just a thought.

**Comment by Nobody-11** [comment] 2015-03-28 04:46
Completed agreed with gomalley411, Ops won't be happy if they got banned without any reasons, they will just appeal the ban and said banned offline, Admins would tell them that they griefed or something like that....

**Comment by JeromSar** [comment] 2015-10-12 06:51
Duplicate of #848

**Closed by JeromSar** 2015-10-12 06:51 UTC
Labels: Duplicate, Issue: Enhancement

**Comment by DUFCLiam** [comment] 2016-03-10 16:58
Not a duplicate @JeromSar
