### ISSUE TITLE
TFM_AdminList.addSuperadmin(player); and TFM_AdminList.removeSuperadmin(player);

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#660] opened 2015-05-21 23:14 UTC
When i was trying to code another command into my plugin(This happend a few weeks ago, Also it wasnt TotalFreedomMod ) Eclipse wanted me to change TFM_AdminList.addSuperadmin(player); to
TFM_AdminList.removeSuperadmin(player); then after i made it that it wanted me to change it back, etc.

**Comment by JeromSar** [comment] 2015-05-22 06:12
Duplicate of #659

**Closed by JeromSar** 2015-05-22 06:12 UTC
