### ISSUE TITLE
Invisibility for admins

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#506] opened 2015-03-16 19:52 UTC
/invis should have a option like /invis on which enabled invisibility for unlimited time for Super Admins and above! This would help because there wouldnt be a constant re-drinking of the invis pots when catching griefers and you wouldn't have to keep re drinking invis pots because this will more likely be for unlimited amount of time! I think this is in the wrong section not sure!

**Comment by Wild1145** [comment] 2015-03-16 21:25
Or we could update to 1.8.3 and use GameMode 3?

**Comment by zD12** [comment] 2015-03-17 17:14
@Wild1145, I don't believe there is a Spigot version that allows Minecraft 1.7.x versions to connect and have Minecraft 1.8.3 features.  It wouldn't work too well, it would just lead to anybody on 1.7.x crashing.  However, we could always switch purely to Minecraft 1.8.3 and allow only users with that version to connect- but that's neglectful and wouldn't help with allowing more people to connect.. 

Speaking of adding this feature, we could always change the config.yml and allow Super Administrators to have Essentials '/vanish' ('/v') instead of just blocking it.  Wouldn't be too difficult.

**Comment by Wild1145** [comment] 2015-03-18 10:36
@zD12 Who said anything about 1.7.X? You wont find ANY spigot versions that allow 1.7.X joining and 1.8.X functionality, because it doesnt work like that. You would need to do a total update to 1.8.3 like it ideally should have been done months ago. 

The essentials vanish is just an invis potion, so rather pointless.

**Comment by OxLemonxO** [comment] 2015-03-19 14:49
There is a plugin that allows 1.8 features on 1.7..
http://www.spigotmc.org/resources/carbon.1258/

**Comment by JeromSar** [comment] 2015-03-19 15:18
@Wild1145 @zD12 I wonder if the new Spigot API for 1.8.3 supports Gamemode 3 and/or if we should be using that instead of the default Player.hidePlayer(Player).

**Comment by Wild1145** [comment] 2015-03-19 17:06
@JeromSar From using 1.8.2 in DarthCraft it is supported, and it works a lot better than setting the player to hidden where its just an invis potion. The only possible problem could be with the all op thing where everyone would in theory have permission to see the hidden players, but I think that you can only see other hidden players in GameMode 3, so as long as we block the ability for players to jump into GM3 we **should** be good.

**Comment by DUFCLiam** [comment] 2015-12-25 14:21
Bump

**Comment by JeromSar** [comment] 2015-12-27 14:50
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/266 actually

**Closed by JeromSar** 2015-12-27 14:50 UTC
Labels: Issue: Enhancement
