### ISSUE TITLE
Hide glist IPs

### ISSUE THREAD

**Issue by GeekGuy432** [TotalFreedom/TotalFreedomMod#804] opened 2015-08-29 13:56 UTC
When a player is banned/unbanned by /glist, their IPs are shown. If the IPs were hidden (they can still be IP banned), it improves privacy.

**Comment by JeromSar** [comment] 2015-08-29 13:58
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/723

**Closed by JeromSar** 2015-08-29 13:58 UTC
Labels: Duplicate, Issue: Enhancement
