### ISSUE TITLE
Ops can do /title

### ISSUE THREAD

**Issue by OliverDatGuy** [TotalFreedom/TotalFreedomMod#648] opened 2015-05-17 20:28 UTC
Very spammy and annoying, it's apparently for super's only but it still works. Fix ASAP please c:

**Comment by zD12** [comment] 2015-05-17 20:29
It's not an issue.  See #646

**Comment by OliverDatGuy** [comment] 2015-05-17 20:30
What're you talking about, it's been blocked but still works.

**Comment by zD12** [comment] 2015-05-17 20:32
@OliverDatGuy, that's because you're an administrator.  It's allowed for administrators, not for operators.

**Comment by OliverDatGuy** [comment] 2015-05-17 20:33
Wrong, tested as an op. It still works.

**Comment by BlooStar** [comment] 2015-05-17 21:09
I can verify that ^

**Comment by PattyToTheWatty** [comment] 2015-05-18 06:50
Admins should be doing /smite. could be annoying.

**Comment by JeromSar** [comment] 2015-05-30 18:03
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/621

**Closed** 2015-05-30 18:04 UTC
Labels: Duplicate, Issue: Enhancement
