### ISSUE TITLE
Custom /seen command for TFM

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#1029] opened 2015-12-29 21:55 UTC
To stop bugs allowing ops to see others ops and admin IPS, Why not make a custom /seen command in TFM?

**Comment by JeromSar** [comment] 2015-12-29 21:56
@LegendIsAwesomes Can you not see that this is a clear duplicate?
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/1028

**Closed by JeromSar** 2015-12-29 21:56 UTC

**Comment by LegendIsAwesomes** [comment] 2015-12-29 21:59
@JeromSar that issue is reporting the bug, This one is suggesting a new command to maybe fix the bug.

**Comment by JeromSar** [comment] 2015-12-29 22:00
@LegendIsAwesomes The fix should be presented in the original issue. Image how many issues we'd have if every possible solution for every problem was made in a new issue.
