### ISSUE TITLE
glist ban reason parameter

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#288] opened 2014-08-20 00:18 UTC
/glist ban name reason

This would be nice so the banned player can see why they got banned if they try to relog. gtfo already has this, so why not glist ban also?

**Comment by JeromSar** [comment] 2016-03-10 16:11
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848

**Closed by JeromSar** 2016-03-10 16:11 UTC
Labels: Issue: Accepted, Issue: Enhancement

**Comment by DUFCLiam** [comment] 2016-03-10 16:37
@JeromSar This is the original issue this is #288 and the duplicate is: #848

**Comment by JeromSar** [comment] 2016-03-10 16:55
@DUFCLiam Corrected.

**Comment by DUFCLiam** [comment] 2016-03-10 16:56
Thank you :) @JeromSar
