### ISSUE TITLE
/smite fix

### ISSUE THREAD

**Issue by AlphaGaming** [TotalFreedom/TotalFreedomMod#846] opened 2015-10-12 06:09 UTC
I really think that it would be useful to add this command enhancement to TFM "/smite [playername] [reason]"

[snip code doesn't go here]

**Comment by JeromSar** [comment] 2015-10-12 06:43
@AlphaGaming I've removed your code from this issues. If you wish to contribute code, please make a PR. :)

**Comment by JeromSar** [comment] 2015-10-12 06:45
Duplicate of #848

**Closed by JeromSar** 2015-10-12 06:45 UTC
Labels: Issue: Enhancement

**Comment by DUFCLiam** [comment] 2016-03-10 16:57
Not a duplicate @JeromSar

**Comment by JeromSar** [comment] 2016-03-10 18:01
@DUFCLiam Yes it is.

**Comment by Adaptified** [comment] 2016-03-10 18:14
@DUFCLiam You need to stop, honestly.
