### ISSUE TITLE
Busy system

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#1483] opened 2016-02-09 19:03 UTC
Why not have a busy system, If a player tries to message an admin but they have /busy enabled they get a message saying 'Adminame is busy please contact another admin' or such.

**Comment by RobinGall2910** [comment] 2016-02-09 22:04
Basically just like DarthCraft's busy system, right @Wild1145?

**Comment by AvalancheYT** [comment] 2016-02-10 05:08
I don't think that would be necessary as us, admins, can just use /afk.

**Comment by xItsNickHD** [comment] 2016-02-10 06:45
I actually like it.

@AvalancheYT, if /afk actually let people not message you, then this would be denied. But instead it doesn't.

**Comment by Wild1145** [comment] 2016-02-10 14:37
That is correct. Though this should be a duplicate as I believe I already raised the issue before...

**Comment by DUFCLiam** [comment] 2016-03-02 12:54
Duplicate of #498

**Closed** 2016-03-02 16:06 UTC
Labels: Duplicate, Issue: Enhancement
