### ISSUE TITLE
Creative PvP: A way to avoid it

### ISSUE THREAD

**Issue by Dusty01** [TotalFreedom/TotalFreedomMod#907] opened 2015-11-28 17:23 UTC
Basically what the title says. Creative pvping is getting annoying. And sometimes we miss some people who do it. Or sometimes, admins are not online and then there is complete chaos. On Imma Freedom, (associated server) creative pvping is completely blocked. I'm not a computer expert, so I don't know how it works, but, It basically doesn't allow any player to hit any other player while in God mode or creative mode. After seeing this I wondered why it isn't implemented in Total Freedom yet. It would make it easier for the admins, and even when we are offline, there wont be any commotion. It would be way better and easier if this was implemented.

**Comment by Verdon-Online** [comment] 2015-11-29 00:11
duplicate of #287

**Closed** 2015-11-29 09:37 UTC

**Comment by Dusty01** [comment] 2015-12-04 13:17
There is a small difference.

**Comment by OnlineRepz** [comment] 2015-12-04 22:27
Comment on that issue. This is still duplicate.
