### ISSUE TITLE
Tempban Broken

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#873] opened 2015-10-20 22:19 UTC
For some reason /tban and /tempban appear to be completely broken... Players can simply login as usual... I am not 100% sure for the reason, however this is what happened earlier: https://www.screenshottr.us/v/e4a36e788c06778161a335d2c22bccd6/88e24849ff664ca19572f5b47c40eaec.png

When you GTFO the player they cannot re-join, but this is a significant pain in the backside.

**Comment by JeromSar** [comment] 2015-12-06 15:48
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/745

**Closed by JeromSar** 2015-12-06 15:48 UTC
Labels: Bug, Duplicate
