### ISSUE TITLE
AutoOP

### ISSUE THREAD

**Issue by RobinGall2910** [TotalFreedom/TotalFreedomMod#1020] opened 2015-12-27 07:52 UTC
Adds a feature that allows the player to be opped on login.
 
Not my idea, it's from @Scarynoises.

Pull Request Number: #1019

**Comment by PattyToTheWatty** [comment] 2015-12-27 07:56
Duplicate.

**Comment by RobinGall2910** [comment] 2015-12-27 07:58
@PattyToTheWatty you're _supposed_ to make a issue once you make a PR.

**Comment by PattyToTheWatty** [comment] 2015-12-27 08:00
I think its the other way around...

**Comment by PattyToTheWatty** [comment] 2015-12-27 08:03
#627

**Comment by DUFCLiam** [comment] 2015-12-27 10:16
@RobinGall2910, Robin @PattyToTheWatty is correct these are the steps to follow:

1. Make an issue

2. Wait for it to be accepted or denied

3. (If accepted) Fork TotalFreedom Mod

4. Post a Project Request linking to this issue

5. Wait for the "PR: Ready to merge" or "PR: Wont merge"

**Comment by JeromSar** [comment] 2015-12-27 14:23
Duplicate of #627
Thanks @PattyToTheWatty

**Closed by JeromSar** 2015-12-27 14:23 UTC
Labels: Issue: Enhancement

**Comment by PattyToTheWatty** [comment] 2015-12-27 20:08
Anytime time! :)
