### ISSUE TITLE
Make execute a TFM  command.

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2004] opened 2017-04-26 04:51 UTC
Make it overrides real console execute, soo it doesn't run or bypass all command blocks.

This has been made to solve the issue with clanforge breaches as they uses execute to gcmd all admins and bypasses all rank checks.

This has been already loaded and tested on TF

**Comment by ghost** [comment] 2017-04-26 16:43
the server jar needs some modding to remove the real execute, i can do it.

i made mark loads a modified server jar.

**Comment by Wild1145** [comment] 2017-04-26 21:27
@marcocorriero So has this already been patched on the server build?

**Comment by ghost** [comment] 2017-05-01 09:44
Yep, it has been patched, with a small edit on totalfreedom server jar and this addiction in tfm

**Comment by mayokek** [comment] 2017-05-18 04:59
The simple patch fix is to change this line (https://github.com/TotalFreedom/TotalFreedomMod/blob/server/src/main/java/me/totalfreedom/totalfreedommod/command/Command_gcmd.java#L32) to
```java
if (plugin.cb.isCommandBlocked(outCommand, player))
```

**Comment by lemonsked** [comment] 2017-06-19 12:05
@mayokek Command_gcmd is not the problem :)

**Comment by mayokek** [comment] 2017-06-19 13:13
I realised.

**Comment by Wild1145** [comment] 2018-05-27 12:48
Now we no longer have Clanforge is this still an issue?

**Comment by Wild1145** [comment] 2018-05-28 13:54
@marcocorriero What was the reason for the issue closing?

**Comment by ghost** [comment] 2018-05-28 14:07
Cause im not  helping tf

________________________________

**Comment by Wild1145** [comment] 2018-05-28 14:24
So given there has been no valuable contribution I'm re-opening until we can validate the issue is in fact solved or no longer relevant.

**Closed as completed** 2018-05-28 14:50 UTC
Labels: Issue: Enhancement, Issue: Currently Patched

**Comment by Wild1145** [comment] 2018-05-28 15:00
So you're going to act like a child. Rasing a new ticket on #2164
