### ISSUE TITLE
Addition to Block /pp Barrier

### ISSUE THREAD

**Issue by mysteriace** [TotalFreedom/TotalFreedomMod#880] opened 2015-10-26 02:17 UTC
Same thing with /pp barrier. As suggested by ChargedCreeper again we should block /pp largeexplode

**Comment by Wild1145** [comment] 2015-10-26 18:01
Edit the original issue.

**Comment by JeromSar** [comment] 2015-10-26 22:43
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/876

**Closed by JeromSar** 2015-10-26 22:43 UTC
Labels: Duplicate, Issue: Enhancement
