### ISSUE TITLE
Command suggestion: /vanish

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1005] opened 2015-12-24 20:04 UTC
Admins can use this to hide/pretend to be offline

Features:

- Vanished
  - You cannot be seen by OPs
  - Will have a rank system like
    - Super Admin can see: OP's, Super Admins
    - Telnet Admin can see: OP's, Super Admins
    - Senior Admin can see: OP's, Super Admins
    - Developer can see: OP's, Super Admins, Telnet Admin, Senior Admin (Steven 
      Lawson(@StevenLawson) and Jerom van der Sar(@JeromSar)   
    - Owner can see: Super Admin, Telnet Admin, Senior Admin, Developer, Other people who fall   
      under Owner in this system
  
- Disables the login message.
    
    - You can join without a login message if you use /vanish (You are added to an array list)
    - This has the system:
    - Super Admin can see: Other Super admins
    - Telnet Admin can see: Super admins, Telnet Admins
    - Senior Admin can see: Super Admins, Telnet Admins, Other Senior Admins
    - Developer can see: Super Admins, Telnet Admin, Senior Admin, Other developers 
      (Steven Lawson(@StevenLawson) and Jerom van der Sar(@JeromSar) they come under                          
      Owner in this System
    - Owner can see: Super Admin, Telnet Admin, Senior Admin, Developer

**Comment by Sabermc7** [comment] 2015-12-24 20:21
Vouch. Just like my suggestion. =)

Just one thing to say: Instead of it disabling the login message. Maybe when a admin does it, it'll do the fake leave message instead "[player] left the game" when the admin executes the /vanish (or alias: /v) command.

**Comment by ValenciaOrange** [comment] 2015-12-24 21:45
I like the rank seeing system but what If a rogue superadmin griefs adminworld in vanish and the only ones online are super admins and they cant see the rogue or report them

**Comment by Sabermc7** [comment] 2015-12-24 22:41
@ValenciaOrange, that's why we have logviewer. Even though the admin is invisible on the server, doesn't mean their commands are invisible as well. =)

**Comment by PacksGamingHD** [comment] 2015-12-25 05:04
why can't all admins see other admins in /vanish

**Comment by Adamx120** [comment] 2015-12-25 10:07
Looks good to me.

**Comment by JeromSar** [comment] 2015-12-25 10:27
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/506

**Closed by JeromSar** 2015-12-25 10:27 UTC
Labels: Issue: Enhancement
