### ISSUE TITLE
Prevent spam with /op

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#953] opened 2015-12-19 15:46 UTC
#954

**Comment by JeromSar** [comment] 2015-12-20 11:45
@DUFCLiam What exactly is the issue here?

**Comment by Wild1145** [comment] 2015-12-20 17:40
Looks like just to have an associated issue with the PR... Kinda completely pointless...

**Comment by OnlineRepz** [comment] 2015-12-20 23:51
Duplicate to some issue.
He wants to prevent people opping opped players

**Comment by JeromSar** [comment] 2015-12-21 14:34
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/538

**Closed by JeromSar** 2015-12-21 14:34 UTC
Labels: Issue: Enhancement
