### ISSUE TITLE
Add clear function to invis

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#978] opened 2015-12-21 06:43 UTC
Invis smite, smiting all invis players

Invis clear, clearing all invis potion from all players

Note: It ain't a duplicate cause #959 is for removing invis smite
And it is an addition /invis clear

**Comment by OnlineRepz** [comment] 2015-12-21 07:42
Duplicate of Issue #959

**Comment by Adamx120** [comment] 2015-12-21 07:50
It isn't you said REPLACE smite with clear

**Comment by OnlineRepz** [comment] 2015-12-21 09:07
@Adamx120, but it's similar to this issue.

**Comment by Adamx120** [comment] 2015-12-21 09:29
But it is problem?

**Comment by Adamx120** [comment] 2015-12-21 09:30
If i make a PR for adding function invis clear, Prozza will say, there are not a pair for my PR, so i created another PR.

**Comment by Wild1145** [comment] 2015-12-21 11:49
This issue likely should be merged with issue #959

**Comment by JeromSar** [comment] 2015-12-21 13:23
The issue is a duplicate. The problem is the same. Wether the solution is different is irrelevant. Closing as duplicate to https://github.com/TotalFreedom/TotalFreedomMod/issues/959

**Closed by JeromSar** 2015-12-21 13:23 UTC
