### ISSUE TITLE
Adding reason parameter to "/noob" and "/tban"

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#988] opened 2015-12-23 08:59 UTC
I'd like
 - /noob ExamplePlayer1 Minor grief
   Output: You have been temporarily banned for five minutes. Please read totalfreedom.me for more info. Reason: %reason

**Comment by JeromSar** [comment] 2015-12-25 09:58
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848

**Closed by JeromSar** 2015-12-25 09:58 UTC
