### ISSUE TITLE
Chat Delay.

### ISSUE THREAD

**Issue by Robolawrence** [TotalFreedom/TotalFreedomMod#719] opened 2015-06-24 02:48 UTC
So I've noticed spambots using RNGs and messages to crash the server lately, so maybe have a very small chat cooldown (like half a second) so it won't be such a problem, as far as load on the server* and spamming clients go? This could also go with commands so that, say, if someone is spamvertising, or if they're spaming //paste they can be controlled a bit easier.
*Not sure if adding a delay would cause ease on the server as far as lagging goes due to how fast the inputs are. I'm not an expert on how all that works.

**Comment by PattyToTheWatty** [comment] 2015-06-24 11:09
Lol, all hail robo! The chat delay person!
Goodbye spammers!
I hope this is emplemented

**Comment by SlicedCaek** [comment] 2015-06-24 11:32
I don't think this would be a good idea...

I tried to implement this into my mod and it fucked up my server chat. Therefore I am against to this idea.

**Comment by JeromSar** [comment] 2015-06-24 11:49
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/677

**Closed by JeromSar** 2015-06-24 11:49 UTC
