### ISSUE TITLE
Make the /list or /who command NOT display hidden admins

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1004] opened 2015-12-24 17:53 UTC
So there's a way admins can make theirself become exactly like Essentials's /vanish (/v) command. Which is:
**/scoreboard teams option [team name] nametagvisibility never** 

This suggestion is, /list or the alias /who will NOT show anyone that is not listed on TAB. Because when a team has the objective on the scoreboard 'nametagvisibility' set to 'never'. It's basically like Essentials's vanish command, all players in the team's name will not show above their name or TAB. Now the only thing to do now is make sure /list or /who doesn't show the hidden admins or the team that has the 'nametagvisibility' set to 'never'. When this is done, admins can now have the option to make themselves invisible as well. We need this anyway because some ops obviously think that when there's no admins on, they think they can get away with breaking major server rules when they don't realize that when we get this updated /list command. It'll be a alternative to Essentials /vanish. Because even opped players wont see the team members who are in the teams.

**Comment by mysteriace** [comment] 2015-12-24 18:00
Vouch!

**Comment by vladvilcu2006** [comment] 2015-12-24 18:08
Vouch. Really needed @JeromSar

**Comment by Lighteh** [comment] 2015-12-24 18:21
Vouch :D

**Comment by ValenciaOrange** [comment] 2015-12-24 21:36
if the admin go rogue, and greifs adminworld, no nametag is not helping it.

**Comment by Sabermc7** [comment] 2015-12-24 21:38
@ValenciaOrange although, just because they're invisible. Doesn't mean their commands wont be logged. Admins can just get their evidence using the logviewer. :)

**Comment by xDestroyer217** [comment] 2015-12-25 01:52
I'm just gonna C&P what I said.


I find this REALLY stupid to believe because we have a rank just for this, its called the one above you, or called, Telnet (Super Admin).

**Comment by ReelPattytothewatty** [comment] 2015-12-25 20:48
That is stupid.

**Comment by Wild1145** [comment] 2015-12-28 00:11
Superseded with the other invisibility command.

**Comment by JeromSar** [comment] 2015-12-28 13:24
@Wild1145 issue #?

**Comment by Wild1145** [comment] 2016-01-01 00:31
@JeromSar Should be merged into the GM 3 implementation style in issue #266 as I belive GM 3 does remove your name from the tab (If it doesn't it should be a part of the command that would be created with #266 anyway).

**Comment by JeromSar** [comment] 2016-01-01 15:59
@Wild1145 I believe Bukkit has an API for removing players from the tab too. We'll have to find out.

Duplicate of #266.

**Closed by JeromSar** 2016-01-01 15:59 UTC
Labels: Issue: Enhancement
