### ISSUE TITLE
Player Avioded Ban 

### ISSUE THREAD

**Issue by ValenciaOrange** [TotalFreedom/TotalFreedomMod#815] opened 2015-09-08 14:37 UTC
http://i.imgur.com/Be0yUzP.png  ChadyPlaysMC  got /noob -ed by me then joins right back. I gave him a gtfo after.
Logs : http://pastebin.com/raw.php?i=66ukKdAC
:see_no_evil:

**Comment by ValenciaOrange** [comment] 2015-09-08 14:46
If you're saying its vpn or ip change its not 
http://pastebin.com/raw.php?i=kSYFvF5D

**Comment by xDestroyer217** [comment] 2015-09-08 15:14
probs the uuid was invalid. big deal.

**Comment by JeromSar** [comment] 2015-09-13 11:16
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/745

**Closed** 2015-09-13 11:16 UTC
Labels: Bug, Duplicate
