### ISSUE TITLE
Prevent creative pvp.

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#825] opened 2015-09-20 18:31 UTC
I am making this issue because my PR is in need of one and i already have the code.

https://github.com/TotalFreedom/TotalFreedomMod/pull/824 is the PR. @JeromSar

**Comment by JeromSar** [comment] 2015-09-21 16:22
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/287

**Comment by LegendIsAwesomes** [comment] 2015-09-21 16:50
Oh okay, there's a PR ready anyways.

**Closed** 2015-10-03 07:12 UTC
Labels: Duplicate, Issue: Enhancement
